# Generated by Django 3.2.12 on 2022-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('second_name', models.TextField(max_length=64)),
                ('phone', models.TextField(max_length=12)),
                ('email', models.TextField()),
                ('age', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
