# Generated by Django 3.2.12 on 2022-03-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0002_alter_danisan_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('second_name', models.TextField(max_length=64)),
                ('phone', models.TextField(max_length=13)),
                ('email', models.TextField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='danisan',
            name='gender',
            field=models.CharField(default='B', max_length=1),
        ),
        migrations.CreateModel(
            name='Randevular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rndTime', models.DateTimeField()),
                ('dnsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rndapp.danisan')),
                ('pskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rndapp.terapist')),
            ],
        ),
    ]
