# Generated by Django 3.2.12 on 2022-03-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0004_alter_randevular_rndtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevular',
            name='rndTime',
        ),
    ]
