# Generated by Django 3.2.12 on 2022-03-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0008_terapist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
    ]
