# Generated by Django 3.2.12 on 2022-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0009_auto_20220326_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('E', 'Erkek'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('E', 'Erkek'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
    ]
