# Generated by Django 3.2.12 on 2022-04-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0013_auto_20220329_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisan',
            name='pskId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rndapp.terapist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
    ]
