# Generated by Django 3.2.12 on 2022-04-26 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0015_auto_20220426_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danisan',
            name='age',
        ),
        migrations.AddField(
            model_name='danisan',
            name='born',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
