# Generated by Django 3.2.12 on 2022-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0018_auto_20220428_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevular',
            name='pskId',
        ),
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('B', 'Belirtilmedi'), ('K', 'Kadın'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('B', 'Belirtilmedi'), ('K', 'Kadın'), ('E', 'Erkek')], default='B', max_length=1),
        ),
    ]
