# Generated by Django 3.2.12 on 2022-04-29 13:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0019_auto_20220428_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='danisan',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
