# Generated by Django 3.2.12 on 2022-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0020_auto_20220429_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevular',
            name='passed',
            field=models.IntegerField(default=0),
        ),
    ]
