# Generated by Django 3.2.12 on 2022-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0021_randevular_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('B', 'Belirtilmedi'), ('K', 'Kadın')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('B', 'Belirtilmedi'), ('K', 'Kadın')], default='B', max_length=1),
        ),
    ]
