# Generated by Django 3.2.12 on 2022-05-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0022_auto_20220501_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
    ]
