# Generated by Django 3.2.12 on 2022-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0023_auto_20220501_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevular',
            name='passed',
        ),
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('B', 'Belirtilmedi'), ('K', 'Kadın')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='01/05/2022 19:47'),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('B', 'Belirtilmedi'), ('K', 'Kadın')], default='B', max_length=1),
        ),
    ]
