# Generated by Django 3.2.12 on 2022-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0024_auto_20220501_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevular',
            name='passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
    ]
