# Generated by Django 3.2.12 on 2022-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0025_auto_20220501_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('B', 'Belirtilmedi'), ('E', 'Erkek'), ('K', 'Kadın')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='01/05/2022 20:48'),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('B', 'Belirtilmedi'), ('E', 'Erkek'), ('K', 'Kadın')], default='B', max_length=1),
        ),
    ]
