# Generated by Django 3.2.12 on 2022-05-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0026_auto_20220501_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='01/05/2022 21:12'),
        ),
    ]
