# Generated by Django 3.2.12 on 2022-05-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0027_alter_randevular_rndtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='01/05/2022 22:04'),
        ),
    ]
