# Generated by Django 3.2.12 on 2022-05-01 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0028_alter_randevular_rndtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 22, 12, 31, 820551)),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('B', 'Belirtilmedi'), ('E', 'Erkek')], default='B', max_length=1),
        ),
    ]
