# Generated by Django 3.2.12 on 2022-05-01 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0029_auto_20220501_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('B', 'Belirtilmedi'), ('K', 'Kadın'), ('E', 'Erkek')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 22, 13, 21, 949660)),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('B', 'Belirtilmedi'), ('K', 'Kadın'), ('E', 'Erkek')], default='B', max_length=1),
        ),
    ]
