# Generated by Django 3.2.12 on 2022-05-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0030_auto_20220501_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('E', 'Erkek'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='01/05/2022 22:27'),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('K', 'Kadın'), ('E', 'Erkek'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
    ]
