# Generated by Django 3.2.12 on 2022-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0031_auto_20220501_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='08/05/2022 20:46'),
        ),
    ]
