# Generated by Django 3.2.12 on 2022-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rndapp', '0033_alter_randevular_rndtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisan',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='randevular',
            name='rndTime',
            field=models.DateTimeField(default='17/05/2022 19:05'),
        ),
        migrations.AlterField(
            model_name='terapist',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Belirtilmedi')], default='B', max_length=1),
        ),
    ]
